### PR TITLE
Always start session on successful auth

### PR DESCRIPTION
**Pull request by smanilov**
This results in automatic login after fingerprint is recognized.

---

Hello there! I couldn't figure out why the special `prompted` logic was there, but I'm sure there is a good reason :)

Could someone more familiar with the codebase please let me know if this approach breaks some valid use-case?

### CODE REVIEW

**Comment by bluesabre** [comment]
At this point in the authentication, it might be possible that PAM has more messages to deliver. But it might also be done in which case this patch would be fine.

@robert-ancell, it's been a decade since you've touched this part of the codebase... but do you have any suggestions here?

**Comment by robert-ancell** [comment]
I think the issue was you could select a user in the UI (e.g. by scrolling to them) and if PAM authenticated without input that would immediately log into that user. This is not necessarily what the user expected - in that case we want them to click a button to confirm they actually want to log in as that user. This makes sense on a command line, as the user explicitly triggered something to do the login (e.g. ran a command or entered a username).

**Comment by bluesabre** [comment]
@robert-ancell That makes sense, thanks!
@smanilov Is there some event that could be captured when doing a fingerprint read? This would probably be the best place to hook in.

**Comment by smanilov** [comment]
Thanks for the reply!

What Robert is saying makes sense to me as well.

> Is there some event that could be captured when doing a fingerprint read? This would probably be the best place to hook in.

As far as I can tell, fingerprint auth happens in the PAM library. It is used by session-child, which is a child process in lightdm.

It seems to me that PAM abstracts away the method of authentication by design (fingerprint in this case), so I think it is unlikely that there could be an event special for the fingerprint auth that could be captured, but ignored for other types of PAM.

Would it be **feasible** to add a configuration flag along the lines of "auto-login-on-successful-pam", so that users could choose the behavior? Option 1 (flag is false): on successful fingerprint read or other PAM -> press button to log in; option 2 (flag is true): on successful fingerprint read or other PAM -> immediately log in.

**Comment by smanilov** [comment]
I just updated the PR to add the configuration option.

Please, let me know what you think :)

**Comment by smanilov** [comment]
Hey, close to 1 year anniversary of the creation of this PR \o/

Could anyone take a look and merge this, if it's okay?

**Comment by smanilov** [comment]
Please see #127 , which simplifies this PR.

**Pull request closed without merging**
